[global]
modules = [
 "logo"
]

[logo]
color = "blue" # can be a hex code, or use the terminal's color, default is blue
text = "Arch" # force override of the name, instead of `uname -o` we will use this instead
