[global]
modules = [
 "logo",
 "kernel"
]

[logo]
color = "blue"
text = "Android"

[kernel]
key = "Kernel"
icon = ""
key-color = "white"
icon-color = "light blue"
format-color = "light blue"
format = "{name} {version}"
