[global]
modules = [
 "logo",
 "user:user",
 "user:hostname",
 "os",
 "host",
 "cpu",
 "kernel",
 "uptime"
]

[logo]
color = "blue"
format = "{distro}"

[user:user]
key = "User"
icon = ""
key-color = "white"
icon-color = "light magenta"
format-color = "light magenta"
format = "{user}"

[user:hostname]
key = "Hostname"
icon = "󰒋"
key-color = "white"
icon-color = "light magenta"
format-color = "light magenta"
format = "{host}"

[os]
key = "OS"
icon = ""
key-color = "white"
icon-color = "light green"
format-color = "light green"
format = "{name} {release} {version} {arch}"

[host]
key = "Host"
icon = "󱤓"
key-color = "white"
icon-color = "light cyan"
format-color = "light cyan"
format = "{manufacturer} {model}"

[cpu]
key = "Cpu"
icon = ""
key-color = "white"
icon-color = "red"
format-color = "red"
format = "{cpu}"

[kernel]
key = "Kernel"
icon = ""
key-color = "white"
icon-color = "light blue"
format-color = "light blue"
format = "{name} {version}"

[uptime]
key = "Uptime"
icon = ""
key-color = "white"
icon-color = "light yellow"
format-color = "light yellow"
format = "{time}"
